# Generated by Django 2.1.2 on 2019-08-15 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0102_auto_20190811_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='detailcloth',
            field=models.CharField(blank=True, max_length=250, verbose_name='Details for required clothing - ആവശ്യമായ വസ്ത്രത്തിന്റെ വിവരങ്ങള്\u200d'),
        ),
        migrations.AlterField(
            model_name='request',
            name='detailfood',
            field=models.CharField(blank=True, max_length=250, verbose_name='Details for required food - ആവശ്യമായ ഭക്ഷണത്തിന്റെ വിവരങ്ങള്\u200d'),
        ),
        migrations.AlterField(
            model_name='request',
            name='detailmed',
            field=models.CharField(blank=True, max_length=250, verbose_name='Details for required medicine - ആവശ്യമായ മരുന്നിന്റെ  വിവരങ്ങള്\u200d'),
        ),
        migrations.AlterField(
            model_name='request',
            name='detailwater',
            field=models.CharField(blank=True, max_length=250, verbose_name='Details for required water - ആവശ്യമായ വെള്ളത്തിന്റെ വിവരങ്ങള്\u200d'),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestee',
            field=models.CharField(max_length=100, verbose_name='Requestee - അപേക്ഷകന്റെ പേര്'),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestee_phone',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Please Enter 10/11 digit mobile number or landline as 0<std code><phone number>', regex='^((\\+91|91|0)[\\- ]{0,1})?[456789]\\d{9}$')], verbose_name='Requestee Phone - അപേക്ഷകന്റെ ഫോണ്\u200d നമ്പര്\u200d'),
        ),
    ]
