# Generated by Django 2.1.2 on 2019-08-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0105_smsjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsjob',
            name='sms_type',
            field=models.CharField(choices=[('consent', 'Consent'), ('info', 'Information')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
