# Generated by Django 2.1.2 on 2019-08-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0106_smsjob_sms_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsjob',
            name='message',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
