# Generated by Django 2.1.2 on 2019-08-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0109_smsjob_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsjob',
            name='message',
            field=models.CharField(blank=True, help_text='This will only be used for     informational messages. For consent messages, a preconfigured message is used', max_length=160, null=True),
        ),
    ]
