# Generated by Django 2.1.2 on 2019-08-18 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0110_auto_20190818_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='smsjob',
            name='area',
            field=models.CharField(blank=True, choices=[('dcr', 'Doctor'), ('hsv', 'Health Services'), ('elw', 'Electrical Works'), ('mew', 'Mechanical Work'), ('cvw', 'Civil Work'), ('plw', 'Plumbing work'), ('vls', 'Vehicle Support'), ('ckg', 'Cooking'), ('rlo', 'Relief operation'), ('cln', 'Cleaning'), ('bot', 'Boat Service'), ('rck', 'Rock Climbing'), ('oth', 'Other')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='smsjob',
            name='district',
            field=models.CharField(blank=True, choices=[('alp', 'Alappuzha - ആലപ്പുഴ'), ('ekm', 'Ernakulam - എറണാകുളം'), ('idk', 'Idukki - ഇടുക്കി'), ('knr', 'Kannur - കണ്ണൂർ'), ('ksr', 'Kasaragod - കാസർഗോഡ്'), ('kol', 'Kollam - കൊല്ലം'), ('ktm', 'Kottayam - കോട്ടയം'), ('koz', 'Kozhikode - കോഴിക്കോട്'), ('mpm', 'Malappuram - മലപ്പുറം'), ('pkd', 'Palakkad - പാലക്കാട്'), ('ptm', 'Pathanamthitta - പത്തനംതിട്ട'), ('tvm', 'Thiruvananthapuram - തിരുവനന്തപുരം'), ('tcr', 'Thrissur - തൃശ്ശൂർ'), ('wnd', 'Wayanad - വയനാട്')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='smsjob',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.VolunteerGroup'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='groups',
            field=models.ManyToManyField(to='mainapp.VolunteerGroup'),
        ),
    ]
